installation of commands

diff --git a/9-installation_of_commands b/9-installation_of_commands
--- a/9-installation_of_commands
+++ b/9-installation_of_commands
@@ -12,4 +12,11 @@ else
 echo "you are running with root access"
 fi
 
-dnf install mysql
+dnf install mysql -y 
+ if [ $? -eq o ]
+ then
+echo "mysql is installing ... success"
+else 
+echo "mysql is failure ..."
+exit 1 
+fi 
